#!/usr/bin/env ruby

# Script to rebuild the project when a file changes.
#
# Runs the make targets given when the script is started.
#
# Usage: ./watchmake examples html
#
# Requires fs-watch. ($ brew install fswatch)
# https://emcrisostomo.github.io/fswatch/getting.html

require "fileutils"

THIS_DIR = File.expand_path("..", __FILE__)

FileUtils.cd THIS_DIR

FSWATCH_COMMAND = "fswatch --latency 0.1 -Ee 'git|build/|elm-stuff/|solver_server/|user_study_logs/|Generated|.DS_Store|watchmake' ."
MAKE_ARGS       = ARGV.size == 0 ? ["html"] : ARGV
MAKE_COMMAND    = "cd src; make #{MAKE_ARGS.join(" ")}"

IO.popen(FSWATCH_COMMAND) do |fswatch|
  puts "Will run `#{MAKE_COMMAND}` on file changes noticed by"
  puts FSWATCH_COMMAND
  loop do
    changed_files = fswatch.readpartial(1_000_000)
    loop do
      sleep(0.1 + 0.1 * Math.log(changed_files.lines.size, 10)) # File changes might still be coming (e.g. git checkout)
      break unless more_changed_files = (fswatch.read_nonblock(1_000_000) rescue nil)
      changed_files << more_changed_files
    end
    puts changed_files
    puts MAKE_COMMAND
    system MAKE_COMMAND
  end
end
