#!/usr/bin/env bash

# Script to rebuild the project when a file changes.
# Does not rebuild the built-in examples.
#
# Usage: ./watchmake
#
# Requires fs-watch. ($ brew install fswatch)
# https://emcrisostomo.github.io/fswatch/getting.html

FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $FILE_DIR

# If you need to work on built-in examples, change to "make prelude examples html"

echo "fswatch -l 0.1 -Ee 'git|build/|elm-stuff/|Generated' . | xargs -ton 1 sh -c 'cd src; make html'"
fswatch -l 0.1 -Ee 'git|build/|elm-stuff/|Generated' . | xargs -ton 1 sh -c 'cd src; make html'
