#!/usr/bin/env sh

# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# -b means no color
ruby $HERE/../reduce_in_filter.rb | $HERE/../reduce-algebra/bin/redcsl -b | ruby $HERE/../reduce_out_filter.rb
