#!/usr/bin/env bash

# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# -b means no color
ruby "$THIS_FILE_DIR/../reduce_in_filter.rb" | $THIS_FILE_DIR/../reduce-algebra/bin/redcsl -b | ruby "$THIS_FILE_DIR/../reduce_out_filter.rb"
