SHELL := /bin/bash

all:
	hyde --serve=.. --autosync

input:
	hyde --backward

output:
	hyde

watch:
	hyde --watch --autosync

install:
	npm install -g http-server-editor
	npm install -g hyde-build-tool